### ISSUE TITLE
Do not show the number of notifications in the icon indicator

### ISSUE THREAD

**Issue by tio-trom** [muravjov/do-not-disturb#2]
Useful extension, thank you! I think though that it defeats the purpose a bit if the extension itself is displaying how many unread notifications you have...
![2018-11-13_17-58_1](https://user-images.githubusercontent.com/38043315/48429678-e7ba5500-e76d-11e8-8c42-fec7be226280.png)
 
It makes you look at that now :D

**Comment by muravjov** [comment]
Resolved with Setting "show-number-of-notifications", commit 4b5ddfb651c37ae15d66a6a89f12d4346860fe63
